A=int(input("enter first number"))
B=int(input("enter second number"))
C=A+B
print("the sum is:",C)   

#A=int(input("enter first number"))
#B=int(input("enter second number"))
#C=A-B
#print("the difference is:",C)

#A=int(input("enter first number"))
#B=int(input("enter second number"))
#C=A*B
#print("the product is:",C)

#A=int(input("enter first number"))
#B=int(input("enter second number"))
#C=A/B
#print("the division is:",C)